// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

#include "mobile.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace mobile {
class MobileAPNRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MobileAPNRequest>
      _instance;
} _MobileAPNRequest_default_instance_;
class MobileAPNResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MobileAPNResponse>
      _instance;
} _MobileAPNResponse_default_instance_;
class MobileDialRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MobileDialRequest>
      _instance;
} _MobileDialRequest_default_instance_;
class MobileDialResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MobileDialResponse>
      _instance;
} _MobileDialResponse_default_instance_;
}  // namespace mobile
namespace protobuf_mobile_2eproto {
static void InitDefaultsMobileAPNRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mobile::_MobileAPNRequest_default_instance_;
    new (ptr) ::mobile::MobileAPNRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mobile::MobileAPNRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MobileAPNRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMobileAPNRequest}, {}};

static void InitDefaultsMobileAPNResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mobile::_MobileAPNResponse_default_instance_;
    new (ptr) ::mobile::MobileAPNResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mobile::MobileAPNResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MobileAPNResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMobileAPNResponse}, {}};

static void InitDefaultsMobileDialRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mobile::_MobileDialRequest_default_instance_;
    new (ptr) ::mobile::MobileDialRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mobile::MobileDialRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MobileDialRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMobileDialRequest}, {}};

static void InitDefaultsMobileDialResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::mobile::_MobileDialResponse_default_instance_;
    new (ptr) ::mobile::MobileDialResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::mobile::MobileDialResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MobileDialResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMobileDialResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_MobileAPNRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_MobileAPNResponse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_MobileDialRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_MobileDialResponse.base);
}

::google::protobuf::Metadata file_level_metadata[4];
const ::google::protobuf::ServiceDescriptor* file_level_service_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile::MobileAPNRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile::MobileAPNRequest, cid_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile::MobileAPNResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile::MobileAPNResponse, apn_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile::MobileAPNResponse, cid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile::MobileAPNResponse, type_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile::MobileDialRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::mobile::MobileDialResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::mobile::MobileAPNRequest)},
  { 6, -1, sizeof(::mobile::MobileAPNResponse)},
  { 14, -1, sizeof(::mobile::MobileDialRequest)},
  { 19, -1, sizeof(::mobile::MobileDialResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::mobile::_MobileAPNRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::mobile::_MobileAPNResponse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::mobile::_MobileDialRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::mobile::_MobileDialResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "mobile.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, file_level_service_descriptors);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014mobile.proto\022\006mobile\"\037\n\020MobileAPNReque"
      "st\022\013\n\003cid\030\002 \001(\r\";\n\021MobileAPNResponse\022\013\n\003"
      "apn\030\001 \001(\t\022\013\n\003cid\030\002 \001(\r\022\014\n\004type\030\003 \001(\r\"\023\n\021"
      "MobileDialRequest\"\024\n\022MobileDialResponse2"
      "\344\001\n\023GetMobileAPNService\022C\n\nMobileDial\022\031."
      "mobile.MobileDialRequest\032\032.mobile.Mobile"
      "DialResponse\022C\n\014GetMobileAPN\022\030.mobile.Mo"
      "bileAPNRequest\032\031.mobile.MobileAPNRespons"
      "e\022C\n\014SetMobileAPN\022\030.mobile.MobileAPNRequ"
      "est\032\031.mobile.MobileAPNResponseB\003\200\001\001b\006pro"
      "to3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 403);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "mobile.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_mobile_2eproto
namespace mobile {

// ===================================================================

void MobileAPNRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MobileAPNRequest::kCidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MobileAPNRequest::MobileAPNRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_mobile_2eproto::scc_info_MobileAPNRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:mobile.MobileAPNRequest)
}
MobileAPNRequest::MobileAPNRequest(const MobileAPNRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  cid_ = from.cid_;
  // @@protoc_insertion_point(copy_constructor:mobile.MobileAPNRequest)
}

void MobileAPNRequest::SharedCtor() {
  cid_ = 0u;
}

MobileAPNRequest::~MobileAPNRequest() {
  // @@protoc_insertion_point(destructor:mobile.MobileAPNRequest)
  SharedDtor();
}

void MobileAPNRequest::SharedDtor() {
}

void MobileAPNRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MobileAPNRequest::descriptor() {
  ::protobuf_mobile_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mobile_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MobileAPNRequest& MobileAPNRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_mobile_2eproto::scc_info_MobileAPNRequest.base);
  return *internal_default_instance();
}


void MobileAPNRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mobile.MobileAPNRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cid_ = 0u;
  _internal_metadata_.Clear();
}

bool MobileAPNRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mobile.MobileAPNRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 cid = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &cid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mobile.MobileAPNRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mobile.MobileAPNRequest)
  return false;
#undef DO_
}

void MobileAPNRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mobile.MobileAPNRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 cid = 2;
  if (this->cid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->cid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:mobile.MobileAPNRequest)
}

::google::protobuf::uint8* MobileAPNRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mobile.MobileAPNRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 cid = 2;
  if (this->cid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->cid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mobile.MobileAPNRequest)
  return target;
}

size_t MobileAPNRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mobile.MobileAPNRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 cid = 2;
  if (this->cid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->cid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MobileAPNRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mobile.MobileAPNRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const MobileAPNRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MobileAPNRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mobile.MobileAPNRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mobile.MobileAPNRequest)
    MergeFrom(*source);
  }
}

void MobileAPNRequest::MergeFrom(const MobileAPNRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mobile.MobileAPNRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.cid() != 0) {
    set_cid(from.cid());
  }
}

void MobileAPNRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mobile.MobileAPNRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MobileAPNRequest::CopyFrom(const MobileAPNRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mobile.MobileAPNRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MobileAPNRequest::IsInitialized() const {
  return true;
}

void MobileAPNRequest::Swap(MobileAPNRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MobileAPNRequest::InternalSwap(MobileAPNRequest* other) {
  using std::swap;
  swap(cid_, other->cid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MobileAPNRequest::GetMetadata() const {
  protobuf_mobile_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mobile_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MobileAPNResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MobileAPNResponse::kApnFieldNumber;
const int MobileAPNResponse::kCidFieldNumber;
const int MobileAPNResponse::kTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MobileAPNResponse::MobileAPNResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_mobile_2eproto::scc_info_MobileAPNResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:mobile.MobileAPNResponse)
}
MobileAPNResponse::MobileAPNResponse(const MobileAPNResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  apn_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.apn().size() > 0) {
    apn_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.apn_);
  }
  ::memcpy(&cid_, &from.cid_,
    static_cast<size_t>(reinterpret_cast<char*>(&type_) -
    reinterpret_cast<char*>(&cid_)) + sizeof(type_));
  // @@protoc_insertion_point(copy_constructor:mobile.MobileAPNResponse)
}

void MobileAPNResponse::SharedCtor() {
  apn_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&cid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&cid_)) + sizeof(type_));
}

MobileAPNResponse::~MobileAPNResponse() {
  // @@protoc_insertion_point(destructor:mobile.MobileAPNResponse)
  SharedDtor();
}

void MobileAPNResponse::SharedDtor() {
  apn_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void MobileAPNResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MobileAPNResponse::descriptor() {
  ::protobuf_mobile_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mobile_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MobileAPNResponse& MobileAPNResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_mobile_2eproto::scc_info_MobileAPNResponse.base);
  return *internal_default_instance();
}


void MobileAPNResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:mobile.MobileAPNResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  apn_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&cid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&cid_)) + sizeof(type_));
  _internal_metadata_.Clear();
}

bool MobileAPNResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mobile.MobileAPNResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string apn = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_apn()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->apn().data(), static_cast<int>(this->apn().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "mobile.MobileAPNResponse.apn"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 cid = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &cid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 type = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:mobile.MobileAPNResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mobile.MobileAPNResponse)
  return false;
#undef DO_
}

void MobileAPNResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mobile.MobileAPNResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string apn = 1;
  if (this->apn().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->apn().data(), static_cast<int>(this->apn().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mobile.MobileAPNResponse.apn");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->apn(), output);
  }

  // uint32 cid = 2;
  if (this->cid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->cid(), output);
  }

  // uint32 type = 3;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->type(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:mobile.MobileAPNResponse)
}

::google::protobuf::uint8* MobileAPNResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mobile.MobileAPNResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string apn = 1;
  if (this->apn().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->apn().data(), static_cast<int>(this->apn().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "mobile.MobileAPNResponse.apn");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->apn(), target);
  }

  // uint32 cid = 2;
  if (this->cid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->cid(), target);
  }

  // uint32 type = 3;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->type(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mobile.MobileAPNResponse)
  return target;
}

size_t MobileAPNResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mobile.MobileAPNResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string apn = 1;
  if (this->apn().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->apn());
  }

  // uint32 cid = 2;
  if (this->cid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->cid());
  }

  // uint32 type = 3;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MobileAPNResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mobile.MobileAPNResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const MobileAPNResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MobileAPNResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mobile.MobileAPNResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mobile.MobileAPNResponse)
    MergeFrom(*source);
  }
}

void MobileAPNResponse::MergeFrom(const MobileAPNResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mobile.MobileAPNResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.apn().size() > 0) {

    apn_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.apn_);
  }
  if (from.cid() != 0) {
    set_cid(from.cid());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void MobileAPNResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mobile.MobileAPNResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MobileAPNResponse::CopyFrom(const MobileAPNResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mobile.MobileAPNResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MobileAPNResponse::IsInitialized() const {
  return true;
}

void MobileAPNResponse::Swap(MobileAPNResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MobileAPNResponse::InternalSwap(MobileAPNResponse* other) {
  using std::swap;
  apn_.Swap(&other->apn_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(cid_, other->cid_);
  swap(type_, other->type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MobileAPNResponse::GetMetadata() const {
  protobuf_mobile_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mobile_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MobileDialRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MobileDialRequest::MobileDialRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_mobile_2eproto::scc_info_MobileDialRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:mobile.MobileDialRequest)
}
MobileDialRequest::MobileDialRequest(const MobileDialRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mobile.MobileDialRequest)
}

void MobileDialRequest::SharedCtor() {
}

MobileDialRequest::~MobileDialRequest() {
  // @@protoc_insertion_point(destructor:mobile.MobileDialRequest)
  SharedDtor();
}

void MobileDialRequest::SharedDtor() {
}

void MobileDialRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MobileDialRequest::descriptor() {
  ::protobuf_mobile_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mobile_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MobileDialRequest& MobileDialRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_mobile_2eproto::scc_info_MobileDialRequest.base);
  return *internal_default_instance();
}


void MobileDialRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mobile.MobileDialRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool MobileDialRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mobile.MobileDialRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:mobile.MobileDialRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mobile.MobileDialRequest)
  return false;
#undef DO_
}

void MobileDialRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mobile.MobileDialRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:mobile.MobileDialRequest)
}

::google::protobuf::uint8* MobileDialRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mobile.MobileDialRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mobile.MobileDialRequest)
  return target;
}

size_t MobileDialRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mobile.MobileDialRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MobileDialRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mobile.MobileDialRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const MobileDialRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MobileDialRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mobile.MobileDialRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mobile.MobileDialRequest)
    MergeFrom(*source);
  }
}

void MobileDialRequest::MergeFrom(const MobileDialRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mobile.MobileDialRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void MobileDialRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mobile.MobileDialRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MobileDialRequest::CopyFrom(const MobileDialRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mobile.MobileDialRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MobileDialRequest::IsInitialized() const {
  return true;
}

void MobileDialRequest::Swap(MobileDialRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MobileDialRequest::InternalSwap(MobileDialRequest* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MobileDialRequest::GetMetadata() const {
  protobuf_mobile_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mobile_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MobileDialResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MobileDialResponse::MobileDialResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_mobile_2eproto::scc_info_MobileDialResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:mobile.MobileDialResponse)
}
MobileDialResponse::MobileDialResponse(const MobileDialResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:mobile.MobileDialResponse)
}

void MobileDialResponse::SharedCtor() {
}

MobileDialResponse::~MobileDialResponse() {
  // @@protoc_insertion_point(destructor:mobile.MobileDialResponse)
  SharedDtor();
}

void MobileDialResponse::SharedDtor() {
}

void MobileDialResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MobileDialResponse::descriptor() {
  ::protobuf_mobile_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mobile_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MobileDialResponse& MobileDialResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_mobile_2eproto::scc_info_MobileDialResponse.base);
  return *internal_default_instance();
}


void MobileDialResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:mobile.MobileDialResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool MobileDialResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:mobile.MobileDialResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:mobile.MobileDialResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:mobile.MobileDialResponse)
  return false;
#undef DO_
}

void MobileDialResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:mobile.MobileDialResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:mobile.MobileDialResponse)
}

::google::protobuf::uint8* MobileDialResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:mobile.MobileDialResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mobile.MobileDialResponse)
  return target;
}

size_t MobileDialResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mobile.MobileDialResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MobileDialResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:mobile.MobileDialResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const MobileDialResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MobileDialResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:mobile.MobileDialResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:mobile.MobileDialResponse)
    MergeFrom(*source);
  }
}

void MobileDialResponse::MergeFrom(const MobileDialResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:mobile.MobileDialResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void MobileDialResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:mobile.MobileDialResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MobileDialResponse::CopyFrom(const MobileDialResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mobile.MobileDialResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MobileDialResponse::IsInitialized() const {
  return true;
}

void MobileDialResponse::Swap(MobileDialResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MobileDialResponse::InternalSwap(MobileDialResponse* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MobileDialResponse::GetMetadata() const {
  protobuf_mobile_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_mobile_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

GetMobileAPNService::~GetMobileAPNService() {}

const ::google::protobuf::ServiceDescriptor* GetMobileAPNService::descriptor() {
  protobuf_mobile_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_mobile_2eproto::file_level_service_descriptors[0];
}

const ::google::protobuf::ServiceDescriptor* GetMobileAPNService::GetDescriptor() {
  return descriptor();
}

void GetMobileAPNService::MobileDial(::google::protobuf::RpcController* controller,
                         const ::mobile::MobileDialRequest*,
                         ::mobile::MobileDialResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method MobileDial() not implemented.");
  done->Run();
}

void GetMobileAPNService::GetMobileAPN(::google::protobuf::RpcController* controller,
                         const ::mobile::MobileAPNRequest*,
                         ::mobile::MobileAPNResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method GetMobileAPN() not implemented.");
  done->Run();
}

void GetMobileAPNService::SetMobileAPN(::google::protobuf::RpcController* controller,
                         const ::mobile::MobileAPNRequest*,
                         ::mobile::MobileAPNResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method SetMobileAPN() not implemented.");
  done->Run();
}

void GetMobileAPNService::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), protobuf_mobile_2eproto::file_level_service_descriptors[0]);
  switch(method->index()) {
    case 0:
      MobileDial(controller,
             ::google::protobuf::down_cast<const ::mobile::MobileDialRequest*>(request),
             ::google::protobuf::down_cast< ::mobile::MobileDialResponse*>(response),
             done);
      break;
    case 1:
      GetMobileAPN(controller,
             ::google::protobuf::down_cast<const ::mobile::MobileAPNRequest*>(request),
             ::google::protobuf::down_cast< ::mobile::MobileAPNResponse*>(response),
             done);
      break;
    case 2:
      SetMobileAPN(controller,
             ::google::protobuf::down_cast<const ::mobile::MobileAPNRequest*>(request),
             ::google::protobuf::down_cast< ::mobile::MobileAPNResponse*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& GetMobileAPNService::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::mobile::MobileDialRequest::default_instance();
    case 1:
      return ::mobile::MobileAPNRequest::default_instance();
    case 2:
      return ::mobile::MobileAPNRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::google::protobuf::Message& GetMobileAPNService::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::mobile::MobileDialResponse::default_instance();
    case 1:
      return ::mobile::MobileAPNResponse::default_instance();
    case 2:
      return ::mobile::MobileAPNResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

GetMobileAPNService_Stub::GetMobileAPNService_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
GetMobileAPNService_Stub::GetMobileAPNService_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
GetMobileAPNService_Stub::~GetMobileAPNService_Stub() {
  if (owns_channel_) delete channel_;
}

void GetMobileAPNService_Stub::MobileDial(::google::protobuf::RpcController* controller,
                              const ::mobile::MobileDialRequest* request,
                              ::mobile::MobileDialResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}
void GetMobileAPNService_Stub::GetMobileAPN(::google::protobuf::RpcController* controller,
                              const ::mobile::MobileAPNRequest* request,
                              ::mobile::MobileAPNResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(1),
                       controller, request, response, done);
}
void GetMobileAPNService_Stub::SetMobileAPN(::google::protobuf::RpcController* controller,
                              const ::mobile::MobileAPNRequest* request,
                              ::mobile::MobileAPNResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(2),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace mobile
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mobile::MobileAPNRequest* Arena::CreateMaybeMessage< ::mobile::MobileAPNRequest >(Arena* arena) {
  return Arena::CreateInternal< ::mobile::MobileAPNRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mobile::MobileAPNResponse* Arena::CreateMaybeMessage< ::mobile::MobileAPNResponse >(Arena* arena) {
  return Arena::CreateInternal< ::mobile::MobileAPNResponse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mobile::MobileDialRequest* Arena::CreateMaybeMessage< ::mobile::MobileDialRequest >(Arena* arena) {
  return Arena::CreateInternal< ::mobile::MobileDialRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::mobile::MobileDialResponse* Arena::CreateMaybeMessage< ::mobile::MobileDialResponse >(Arena* arena) {
  return Arena::CreateInternal< ::mobile::MobileDialResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
