// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mobile.proto

#ifndef PROTOBUF_INCLUDED_mobile_2eproto
#define PROTOBUF_INCLUDED_mobile_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_mobile_2eproto 

namespace protobuf_mobile_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_mobile_2eproto
namespace mobile {
class MobileAPNRequest;
class MobileAPNRequestDefaultTypeInternal;
extern MobileAPNRequestDefaultTypeInternal _MobileAPNRequest_default_instance_;
class MobileAPNResponse;
class MobileAPNResponseDefaultTypeInternal;
extern MobileAPNResponseDefaultTypeInternal _MobileAPNResponse_default_instance_;
class MobileDialRequest;
class MobileDialRequestDefaultTypeInternal;
extern MobileDialRequestDefaultTypeInternal _MobileDialRequest_default_instance_;
class MobileDialResponse;
class MobileDialResponseDefaultTypeInternal;
extern MobileDialResponseDefaultTypeInternal _MobileDialResponse_default_instance_;
}  // namespace mobile
namespace google {
namespace protobuf {
template<> ::mobile::MobileAPNRequest* Arena::CreateMaybeMessage<::mobile::MobileAPNRequest>(Arena*);
template<> ::mobile::MobileAPNResponse* Arena::CreateMaybeMessage<::mobile::MobileAPNResponse>(Arena*);
template<> ::mobile::MobileDialRequest* Arena::CreateMaybeMessage<::mobile::MobileDialRequest>(Arena*);
template<> ::mobile::MobileDialResponse* Arena::CreateMaybeMessage<::mobile::MobileDialResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace mobile {

// ===================================================================

class MobileAPNRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mobile.MobileAPNRequest) */ {
 public:
  MobileAPNRequest();
  virtual ~MobileAPNRequest();

  MobileAPNRequest(const MobileAPNRequest& from);

  inline MobileAPNRequest& operator=(const MobileAPNRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MobileAPNRequest(MobileAPNRequest&& from) noexcept
    : MobileAPNRequest() {
    *this = ::std::move(from);
  }

  inline MobileAPNRequest& operator=(MobileAPNRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MobileAPNRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MobileAPNRequest* internal_default_instance() {
    return reinterpret_cast<const MobileAPNRequest*>(
               &_MobileAPNRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(MobileAPNRequest* other);
  friend void swap(MobileAPNRequest& a, MobileAPNRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MobileAPNRequest* New() const final {
    return CreateMaybeMessage<MobileAPNRequest>(NULL);
  }

  MobileAPNRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MobileAPNRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MobileAPNRequest& from);
  void MergeFrom(const MobileAPNRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MobileAPNRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 cid = 2;
  void clear_cid();
  static const int kCidFieldNumber = 2;
  ::google::protobuf::uint32 cid() const;
  void set_cid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:mobile.MobileAPNRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 cid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_mobile_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MobileAPNResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mobile.MobileAPNResponse) */ {
 public:
  MobileAPNResponse();
  virtual ~MobileAPNResponse();

  MobileAPNResponse(const MobileAPNResponse& from);

  inline MobileAPNResponse& operator=(const MobileAPNResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MobileAPNResponse(MobileAPNResponse&& from) noexcept
    : MobileAPNResponse() {
    *this = ::std::move(from);
  }

  inline MobileAPNResponse& operator=(MobileAPNResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MobileAPNResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MobileAPNResponse* internal_default_instance() {
    return reinterpret_cast<const MobileAPNResponse*>(
               &_MobileAPNResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(MobileAPNResponse* other);
  friend void swap(MobileAPNResponse& a, MobileAPNResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MobileAPNResponse* New() const final {
    return CreateMaybeMessage<MobileAPNResponse>(NULL);
  }

  MobileAPNResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MobileAPNResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MobileAPNResponse& from);
  void MergeFrom(const MobileAPNResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MobileAPNResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string apn = 1;
  void clear_apn();
  static const int kApnFieldNumber = 1;
  const ::std::string& apn() const;
  void set_apn(const ::std::string& value);
  #if LANG_CXX11
  void set_apn(::std::string&& value);
  #endif
  void set_apn(const char* value);
  void set_apn(const char* value, size_t size);
  ::std::string* mutable_apn();
  ::std::string* release_apn();
  void set_allocated_apn(::std::string* apn);

  // uint32 cid = 2;
  void clear_cid();
  static const int kCidFieldNumber = 2;
  ::google::protobuf::uint32 cid() const;
  void set_cid(::google::protobuf::uint32 value);

  // uint32 type = 3;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  ::google::protobuf::uint32 type() const;
  void set_type(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:mobile.MobileAPNResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr apn_;
  ::google::protobuf::uint32 cid_;
  ::google::protobuf::uint32 type_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_mobile_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MobileDialRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mobile.MobileDialRequest) */ {
 public:
  MobileDialRequest();
  virtual ~MobileDialRequest();

  MobileDialRequest(const MobileDialRequest& from);

  inline MobileDialRequest& operator=(const MobileDialRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MobileDialRequest(MobileDialRequest&& from) noexcept
    : MobileDialRequest() {
    *this = ::std::move(from);
  }

  inline MobileDialRequest& operator=(MobileDialRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MobileDialRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MobileDialRequest* internal_default_instance() {
    return reinterpret_cast<const MobileDialRequest*>(
               &_MobileDialRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(MobileDialRequest* other);
  friend void swap(MobileDialRequest& a, MobileDialRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MobileDialRequest* New() const final {
    return CreateMaybeMessage<MobileDialRequest>(NULL);
  }

  MobileDialRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MobileDialRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MobileDialRequest& from);
  void MergeFrom(const MobileDialRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MobileDialRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:mobile.MobileDialRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_mobile_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class MobileDialResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:mobile.MobileDialResponse) */ {
 public:
  MobileDialResponse();
  virtual ~MobileDialResponse();

  MobileDialResponse(const MobileDialResponse& from);

  inline MobileDialResponse& operator=(const MobileDialResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MobileDialResponse(MobileDialResponse&& from) noexcept
    : MobileDialResponse() {
    *this = ::std::move(from);
  }

  inline MobileDialResponse& operator=(MobileDialResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MobileDialResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MobileDialResponse* internal_default_instance() {
    return reinterpret_cast<const MobileDialResponse*>(
               &_MobileDialResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(MobileDialResponse* other);
  friend void swap(MobileDialResponse& a, MobileDialResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MobileDialResponse* New() const final {
    return CreateMaybeMessage<MobileDialResponse>(NULL);
  }

  MobileDialResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<MobileDialResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const MobileDialResponse& from);
  void MergeFrom(const MobileDialResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MobileDialResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:mobile.MobileDialResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_mobile_2eproto::TableStruct;
};
// ===================================================================

class GetMobileAPNService_Stub;

class GetMobileAPNService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline GetMobileAPNService() {};
 public:
  virtual ~GetMobileAPNService();

  typedef GetMobileAPNService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void MobileDial(::google::protobuf::RpcController* controller,
                       const ::mobile::MobileDialRequest* request,
                       ::mobile::MobileDialResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void GetMobileAPN(::google::protobuf::RpcController* controller,
                       const ::mobile::MobileAPNRequest* request,
                       ::mobile::MobileAPNResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void SetMobileAPN(::google::protobuf::RpcController* controller,
                       const ::mobile::MobileAPNRequest* request,
                       ::mobile::MobileAPNResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GetMobileAPNService);
};

class GetMobileAPNService_Stub : public GetMobileAPNService {
 public:
  GetMobileAPNService_Stub(::google::protobuf::RpcChannel* channel);
  GetMobileAPNService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~GetMobileAPNService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements GetMobileAPNService ------------------------------------------

  void MobileDial(::google::protobuf::RpcController* controller,
                       const ::mobile::MobileDialRequest* request,
                       ::mobile::MobileDialResponse* response,
                       ::google::protobuf::Closure* done);
  void GetMobileAPN(::google::protobuf::RpcController* controller,
                       const ::mobile::MobileAPNRequest* request,
                       ::mobile::MobileAPNResponse* response,
                       ::google::protobuf::Closure* done);
  void SetMobileAPN(::google::protobuf::RpcController* controller,
                       const ::mobile::MobileAPNRequest* request,
                       ::mobile::MobileAPNResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GetMobileAPNService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MobileAPNRequest

// uint32 cid = 2;
inline void MobileAPNRequest::clear_cid() {
  cid_ = 0u;
}
inline ::google::protobuf::uint32 MobileAPNRequest::cid() const {
  // @@protoc_insertion_point(field_get:mobile.MobileAPNRequest.cid)
  return cid_;
}
inline void MobileAPNRequest::set_cid(::google::protobuf::uint32 value) {
  
  cid_ = value;
  // @@protoc_insertion_point(field_set:mobile.MobileAPNRequest.cid)
}

// -------------------------------------------------------------------

// MobileAPNResponse

// string apn = 1;
inline void MobileAPNResponse::clear_apn() {
  apn_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MobileAPNResponse::apn() const {
  // @@protoc_insertion_point(field_get:mobile.MobileAPNResponse.apn)
  return apn_.GetNoArena();
}
inline void MobileAPNResponse::set_apn(const ::std::string& value) {
  
  apn_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mobile.MobileAPNResponse.apn)
}
#if LANG_CXX11
inline void MobileAPNResponse::set_apn(::std::string&& value) {
  
  apn_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mobile.MobileAPNResponse.apn)
}
#endif
inline void MobileAPNResponse::set_apn(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  apn_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mobile.MobileAPNResponse.apn)
}
inline void MobileAPNResponse::set_apn(const char* value, size_t size) {
  
  apn_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mobile.MobileAPNResponse.apn)
}
inline ::std::string* MobileAPNResponse::mutable_apn() {
  
  // @@protoc_insertion_point(field_mutable:mobile.MobileAPNResponse.apn)
  return apn_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MobileAPNResponse::release_apn() {
  // @@protoc_insertion_point(field_release:mobile.MobileAPNResponse.apn)
  
  return apn_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MobileAPNResponse::set_allocated_apn(::std::string* apn) {
  if (apn != NULL) {
    
  } else {
    
  }
  apn_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), apn);
  // @@protoc_insertion_point(field_set_allocated:mobile.MobileAPNResponse.apn)
}

// uint32 cid = 2;
inline void MobileAPNResponse::clear_cid() {
  cid_ = 0u;
}
inline ::google::protobuf::uint32 MobileAPNResponse::cid() const {
  // @@protoc_insertion_point(field_get:mobile.MobileAPNResponse.cid)
  return cid_;
}
inline void MobileAPNResponse::set_cid(::google::protobuf::uint32 value) {
  
  cid_ = value;
  // @@protoc_insertion_point(field_set:mobile.MobileAPNResponse.cid)
}

// uint32 type = 3;
inline void MobileAPNResponse::clear_type() {
  type_ = 0u;
}
inline ::google::protobuf::uint32 MobileAPNResponse::type() const {
  // @@protoc_insertion_point(field_get:mobile.MobileAPNResponse.type)
  return type_;
}
inline void MobileAPNResponse::set_type(::google::protobuf::uint32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:mobile.MobileAPNResponse.type)
}

// -------------------------------------------------------------------

// MobileDialRequest

// -------------------------------------------------------------------

// MobileDialResponse

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mobile

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_mobile_2eproto
